# fly.toml app configuration file generated for talks-mt on 2023-05-17T19:01:02-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "talks-mt"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  protocol = "tcp"
  [http_service.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 500

# [[services]]
#   protocol = "tcp"
#   internal_port = 8080
#   processes = ["app"]

#   [[services.ports]]
#     port = 80
#     handlers = ["http"]
#     force_https = true

#   [[services.ports]]
#     port = 443
#     handlers = ["tls", "http"]
#   [services.concurrency]
#     type = "connections"
#     hard_limit = 25
#     soft_limit = 20

#   [[services.tcp_checks]]
#     interval = "15s"
#     timeout = "2s"
#     grace_period = "1s"
#     restart_limit = 0
