service: floqars
frameworkVersion: ">=1.28.0 <2.0.0"
provider:
  name: aws
  runtime: go1.x
  profile: personal
  region: ${opt:region}
  versionFunctions: false
  memorySize: 1024
  timeout: 30
  endpointType: regional
package:
 exclude:
   - ./**
 include:
   - ./bin/**
functions:
  healthCheck:
    handler: bin/api/health/check
    events:
        - http:
            path: /healthy
            method: get
  # ...